repos:
  # Isort: Python import linter/formatter
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        types: [ python ]
  # Black: Python code formatter
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  # Flake8: Python linter
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  # Mypy: Python type-checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        args: ['--show-error-codes', '--warn-unused-ignores']
        exclude: 'bin/|docs/|examples/|setup.py'
        additional_dependencies: [types-freezegun, types-python-dateutil]
