name: Test pull request
on: pull_request
jobs:
  tox:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Temporarily pin Python to 3.10.6 because 3.10.7 causes issues with mypy. This can be
        # unpinned once the mypy bugfix is released in 0.980. For more, see:
        #   https://insitro.atlassian.net/browse/DE-6251
        python: ['3.6', '3.7', '3.8', '3.9', '3.10.6']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install --upgrade pip
      - run: sudo apt-get install graphviz graphviz-dev
      - run: pip install tox
      - run: tox -e py
  test-postgres:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - run: sudo apt-get install graphviz graphviz-dev
      - run: make test-postgres
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - run: sudo apt-get install graphviz graphviz-dev
      - run: make lint
